lib/angio_web/router.ex
defmodule AngioWeb.Router do
  use AngioWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/graphql", Absinthe.Plug, schema: AngioWeb.Schema)

  forward(
    "/graphiql",
    Absinthe.Plug.GraphiQL,
    schema: AngioWeb.Schema,
    interface: :simple,
    context: %{pubsub: AngioWeb.Endpoint}
  )

  scope "/", AngioWeb do
    pipe_through(:browser)
    live("/counter", CounterLive)

    #    live "/thermostat", ThermostatLive
    # in Index
    # <li><%= link "Thermostat", to: Routes.live_path(@conn, AngioWeb.ThermostatLive) %></li>

    get("/", PageController, :index)
    post("/patients/search_patients", PatientController, :search_patients)
    ########Routes for field Help
    post("/definitions/search_instructions", DefinitionController, :search_instructions)
    post( "/definitions/search_support_definitions",  DefinitionController, :search_support_definitions)
    post("/definitions/search_notes", DefinitionController, :search_notes)
    post("/definitions/search_option_definitions",DefinitionController,:search_option_definitions)
       #####################
    post("/definitions/search_definitions", DefinitionController, :search_definitions)
    post("/defs_tables/search_in_tables", Defs_tableController, :search_in_tables)

    resources "/patients", PatientController, as: :pt do
      # resources("/contacts", ContactController)
      ########## CORONARY ANGIO#################
      resources(
        "/info_coronaries",
        Info_coronaryController,
        only: [:index, :new, :create],
        as: :angio
      )

      resources "/info_coronaries", Info_coronaryController,
        except: [:index, :new, :create],
        as: :angio do
        resources("/care_episodes", Care_episodeController, as: :episode)
        resources("/proc_episodes", Proc_episodeController, as: :proc_episode)
        resources("/cor_collaterals", Cor_collateralController, as: :collateral)
        resources("/cor_anatomies", Cor_anatomyController, as: :anatomy)
        resources("/cor_lesions", Cor_lesionController, as: :lesion)
        resources("/cath_grafts", Cath_graftController, as: :graft)
        resources("/sats_pressures", Sats_pressureController, as: :satpres)

        resources("/angio_report", Angio_reportController, as: :report)
        post("/choose_report", Angio_reportController, :choose_report)
        resources("/Cor_tree", Cor_treeController, as: :cor_tree)
        
        # resources("/reasons", ReasonController)
        # resources("/cath_clinicals", Cath_clinicalController, as: :clinical)
        # resources("/cath_stresses", Cath_stressController, as: :stress)
        resources("/cath_events", Cath_eventController, as: :event)
        # resources("/cath_report", Cath_reportController, as: :cath_report)
        resources("/lventricles", LventricleController, as: :lv)
        resources("/cath_meds", Cath_medController, as: :cathmed)
        resources("/cath_radiations", Cath_radiationController, as: :radiation)
      end

      ## end for info_coronaries
    end

    ## end for partients
    ########## DEFINITIONS OF FIELDS #########
    resources("/defs_tables", Defs_tableController)

    resources "/definitions", DefinitionController do
      resources("/defs_sentences", Defs_sentenceController)
      resources("/defs_codes", Defs_codeController)

      resources "/defs_options", Defs_optionController do
        resources("/opts_codes", Opts_codeController, only: [:index, :new, :create])
        resources("/opts_codes", Opts_codeController)
        resources("/opts_sentences", Opts_sentenceController)
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", AngioWeb do
  #   pipe_through :api
  # end
end

lib/angio/caths/info_coronary.ex
defmodule Angio.Caths.Info_coronary do
  use Ecto.Schema
  import Ecto.Changeset

  schema "info_coronaries" do
    field(:cor_les_count, :string)
    field(:icd10cm_code_1, :string)
    field(:icd10cm_code_2, :string)
    field(:icd10cm_code_3, :string)
    field(:icd10cm_code_4, :string)
    field(:info_cor_anomalies_yn, :boolean, default: false)
    field(:info_cor_arrival_dt, :date)
    field(:info_cor_arrival_tm, :time)
    field(:info_cor_cabg_prior_dt, :date)
    field(:info_cor_date, :date)
    field(:info_cor_diagnostic_status, :string)
    field(:info_cor_dis_ves_num, :string)
    field(:info_cor_end_tm, :time)
    field(:info_cor_grafts_dis_yn, :boolean, default: false)
    field(:info_cor_grafts_implanted_num, :string)
    field(:info_cor_grafts_patent_num, :string)
    field(:info_cor_grafts_yn, :boolean, default: false)
    field(:info_cor_main_reason, :string)
    field(:info_cor_normal_natives_yn, :boolean, default: false)
    field(:info_cor_notes, :string)
    field(:info_cor_prior_interv_yn, :boolean, default: false)
    field(:info_cor_rx_recommend, :string)
    field(:info_cor_start_tm, :time)
    field(:info_exam_num, :string)
    field(:patient_id, :integer)

    has_many(
      :cor_lesions,
      Angio.Caths.Cor_lesion,
      foreign_key: :info_coronary_id
    )

    has_many(
      :cath_grafts,
      Angio.Caths.Cath_graft,
      foreign_key: :info_coronary_id
    )

    has_many(
      :cor_collaterals,
      Angio.Caths.Cor_collateral,
      foreign_key: :info_coronary_id
    )

    has_many(
      :care_episodes,
      Angio.Caths.Care_episode,
      foreign_key: :info_coronary_id
    )

    has_many(
      :proc_episodes,
      Angio.Caths.Proc_episode,
      foreign_key: :info_coronary_id
    )

    has_many(
      :cath_radiations,
      Angio.Caths.Cath_radiation,
      foreign_key: :info_coronary_id
    )

    has_many(
      :cath_events,
      Angio.Caths.Cath_event,
      foreign_key: :info_coronary_id
    )

    has_many(
      :lventricles,
      Angio.Caths.Lventricle,
      foreign_key: :info_coronary_id
    )

    has_many(
      :cath_meds,
      Angio.Caths.Cath_med,
      foreign_key: :info_coronary_id
    )

    has_many(
      :cor_anatomies,
      Angio.Caths.Cor_anatomy,
      foreign_key: :info_coronary_id
    )

    has_many(
      :sats_pressures,
      Angio.Caths.Sats_pressure,
      foreign_key: :info_coronary_id
    )

    timestamps()
  end

  @doc false
  def changeset(info_coronary, attrs) do
    info_coronary
    |> cast(attrs, [
      :info_cor_diagnostic_status,
      :info_cor_date,
      :info_cor_arrival_dt,
      :info_cor_arrival_tm,
      :info_cor_start_tm,
      :info_cor_end_tm,
      :info_exam_num,
      :info_cor_main_reason,
      :icd10cm_code_1,
      :icd10cm_code_2,
      :icd10cm_code_3,
      :icd10cm_code_4,
      :info_cor_normal_natives_yn,
      :info_cor_anomalies_yn,
      :info_cor_dis_ves_num,
      :info_cor_prior_interv_yn,
      :info_cor_grafts_yn,
      :info_cor_grafts_dis_yn,
      :info_cor_cabg_prior_dt,
      :info_cor_grafts_implanted_num,
      :info_cor_grafts_patent_num,
      :info_cor_rx_recommend,
      :info_cor_notes,
      :cor_les_count,
      :patient_id
    ])
    # |> validate_required([:info_cor_diagnostic_status,  :info_cor_date, :info_cor_arrival_dt, :info_cor_arrival_tm, :info_cor_start_tm, :info_cor_end_tm, :info_exam_num, :info_cor_main_reason, :icd10cm_code_1, :icd10cm_code_2, :icd10cm_code_3, :"", :icd10cm_code_4, :info_cor_normal_natives_yn, :info_cor_anomalies_yn, :info_cor_dis_ves_num, :info_cor_prior_interv_yn, :info_cor_grafts_yn, :info_cor_grafts_dis_yn, :info_cor_cabg_prior_dt, :info_cor_grafts_implanted_num, :info_cor_grafts_patent_num, :info_cor_rx_recommend, :info_cor_notes, :cor_les_count])
    |> validate_required([])
  end
end

lib/angio_web/controllers/info_coronary_controller.ex
defmodule AngioWeb.Info_coronaryController do
  use AngioWeb, :controller
  # import PhoenixGon.Controller

  alias Angio.Caths
  alias Angio.Caths.Info_coronary
  alias Angio.Repo
  plug(:assign_patient)

  def index(conn, _params) do
    # conn = put_gon(conn, controller: put_gon)

    info_coronaries = Angio.Repo.all(Ecto.assoc(conn.assigns[:patient], :info_coronaries))
    render(conn, "index.html", info_coronaries: info_coronaries)
  end

  def new(conn, _params) do
    changeset = Caths.change_info_coronary(%Info_coronary{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"info_coronary" => info_coronary_params, "patient_id" => patient_id}) do
    changeset =
      conn.assigns[:patient]
      |> Ecto.build_assoc(:info_coronaries)
      |> Angio.Caths.Info_coronary.changeset(info_coronary_params)

    case Repo.insert(changeset) do
      # case Caths.create_info_coronary(info_coronary_params) do
      {:ok, _info_coronary} ->
        conn
        |> put_flash(:info, "Info coronary created successfully.")
        |> redirect(
          to:
            Routes.pt_angio_path(
              conn,
              :index,
              conn.assigns[:patient]
            )
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def create_1(conn, %{"info_coronary" => info_coronary_params}) do
    changeset =
      conn.assigns[:patient]
      |> Ecto.build_assoc(:info_coronaries)
      |> Info_coronary.changeset(info_coronary_params)

    case Angio.Repo.insert(changeset) do
      {:ok, _info_coronary} ->
        conn
        |> put_flash(:info, "General Information For Angio created successfully.")
        |> redirect(to: Routes.pt_angio_path(conn, :index, conn.assigns[:patient]))

      {:error, changeset} ->
        conn
        |> put_flash(:alert, "Unable to create General Info For Angio")

        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    info_coronary = Caths.get_info_coronary!(id)
    render(conn, "show.html", info_coronary: info_coronary)
  end

  def edit(conn, %{"id" => id}) do
    info_coronary =
      Repo.get!(
        Ecto.assoc(
          conn.assigns[:patient],
          :info_coronaries
        ),
        id
      )

    changeset = Caths.change_info_coronary(info_coronary)
    render(conn, "edit.html", info_coronary: info_coronary, changeset: changeset)
  end

  def update(conn, %{"id" => id, "info_coronary" => info_coronary_params}) do
    info_coronary = Caths.get_info_coronary!(id)

    case Caths.update_info_coronary(info_coronary, info_coronary_params) do
      {:ok, _info_coronary} ->
        conn
        |> put_flash(:info, "Info coronary updated successfully.")
        # |> redirect(to: Routes.pt_angio_path(conn, :show, conn.assigns[:patient], id))
        |> redirect(to: Routes.pt_angio_path(conn, :index, conn.assigns[:patient]))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", info_coronary: info_coronary, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    info_coronary = Caths.get_info_coronary!(id)
    {:ok, _info_coronary} = Caths.delete_info_coronary(info_coronary)

    conn
    |> put_flash(:info, "Record For Info coronary deleted successfully")
    # |> redirect(to: Routes.pt_angio_path(conn, :index))
    |> redirect(to: Routes.pt_angio_path(conn, :index, conn.assigns[:patient]))
  end

  ###############
  defp assign_patient(conn, _opts) do
    case conn.params do
      %{"patient_id" => patient_id} ->
        case Angio.Repo.get(Angio.Persons.Patient, patient_id) do
          # nil -> invalid_user(conn)
          patient ->
            assign(conn, :patient, patient)
        end

      _ ->
        conn
    end
  end

  ##############
end

lib/angio_web/views/info_coronary_view.ex
defmodule AngioWeb.Info_coronaryView do
  use AngioWeb, :view


end

lib/angio_web/templates/info_coronary/edit.html.eex
<h4 class="title is-4 has-text-centered" >Editing  Cath Status - Dates - Reasons ...  </h4>

<div class="element_info">
    Patient :
    <%= render  AngioWeb.SharedView, "_patient_info.html", patient: @patient %>
</div>


<%= render "form.html", changeset: @changeset,
        patient: @patient,
action: Routes.pt_angio_path(@conn, :update,
@patient, @info_coronary ) %>

 <span>
         <%= link "Back To Angio  List", to: Routes.pt_angio_path(@conn, :index, @patient) , class: "button is-link "%>
</span>

lib/angio_web/templates/info_coronary/index.html.eex
<div class="title_form">
<h4 class="title is-4 has-text-centered" >Listing Cath Lab Admissions </h4>
</div>

<div class="element_info">
    Patient :
    <%= render  AngioWeb.SharedView, "_patient_info.html", patient: @patient %>
</div>

<% alias Angio.Canons, as: Query %>
<%#= render  AngioWeb.SharedView, "_menu_info_coronary.html", conn: @conn,
patient: @patient,
info_coronary: @info_coronary,
assigns %>

<%#= render  AngioWeb.SharedView, "_menu_info_coronary.html", assigns %>

<table class="table is-bordered
                    is-striped
                    is-full-width
                    is-hoverable">
  <thead class="thead">
    <tr>
  
      <th>Angio Status</th>
      <th>Angio date</th>
      <th>Lab Exam Num</th>
      <th>Main reason</th>
      <th>Normal natives?</th>
      <th>Vessels Diseased</th>
      <th>Prior Interv</th>
      <th>Grafts? </th>
  <!--------------
      <th> LiveView</th>
     ---------->
      <th>
            <span>
         <i class="fa  fa-book"
          style="font-size:20px;color:#053eff;text-align:center;">
          </i>
         </span>
      Report
      
      </th>
      <th>
            <span>
         <i class="fa  fa-image"
          style="font-size:20px;color:#053eff;text-align:center;">
          </i>
         </span>
      Graphics
      
      </th>
      <th>
          <span>
         <i class="fa  fa-flag"
          style="font-size:20px;color:#053eff;text-align:center;">
          </i>
          </span>
      Menu
      
      
      </th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>


    </tr>
  </thead>
  <tbody>
<%= for info_coronary <- @info_coronaries do %>
    <tr>

      <td>
       <% s_status =  Query.select_options("info_cor_diagnostic_status") %>
 <% v_status = info_coronary.info_cor_diagnostic_status  %>
  <ul class="list-group">
<%= raw(Query.convert_select_key( s_status, v_status)) %>
</ul>

      </td>
      <td>
        <strong>
        <%= info_coronary.info_cor_date %>
        </strong>
      </td>
      <td><%= info_coronary.info_exam_num %></td>



     <td>
<% s_reason =  Query.select_options("info_cor_main_reason") %>
 <% v_reason = info_coronary.info_cor_main_reason  %>
  <ul class="list-group">
<%= raw(Query.convert_select_key( s_reason, v_reason)) %>
</ul>
     </td>
      <td><%= Query.convert_true_false(info_coronary.info_cor_normal_natives_yn) %></td>

      <td><%= info_coronary.info_cor_dis_ves_num %></td>
      <td><%= Query.convert_true_false( info_coronary.info_cor_prior_interv_yn)%></td>
      <td><%=  Query.convert_true_false(info_coronary.info_cor_grafts_yn) %></td>

      </td>
<!----
<td>
<%= link "Counter", to: Routes.live_path(@conn, AngioWeb.CounterLive) %>
</td>
---->
      <td>
     <span><%= link "Text Report Summary", to: Routes.pt_angio_report_path(@conn, 
      :show,
      @patient, 
      info_coronary, info_coronary.id), 
      class: "button is-link is-small is-fullwidth" %></span>
      </td>

       <td>
     <span><%= link "Coronary Sketch ", to: Routes.pt_angio_cor_tree_path(@conn, 
      :show,
      @patient, 
      info_coronary, info_coronary.id), 
      class: "button is-link is-small is-fullwidth" %></span>
      </td>

      <td>

 <%= render  AngioWeb.SharedView, "_menu_info_coronary.html",
conn: @conn, patient: @patient, info_coronary: info_coronary %>

        </td>
           <td>
        <span><%= link "Show", to: Routes.pt_angio_path(@conn, :show,
@patient,info_coronary), class: "button is-link is-small is-fullwidth" %></span>
      
      </td>
      <td>
        <span><%= link "Edit", to: Routes.pt_angio_path(@conn,
         :edit, @patient,info_coronary), class: "button is-link is-small is-fullwidth" %></span>

      </td>

      <td>
          <span>
            <%= link "Delete", to: Routes.pt_angio_path(@conn, :delete, @patient, info_coronary), method: :delete, data: [confirm: "Are you sure?"], class: " button is-danger is-small is-fullwidth" %>
        </span>

      </td>
    </tr>
<% end %>
  </tbody>

</table>

<span><%= link "New Cath Lab Admission",
      to: Routes.pt_angio_path(@conn, :new, @patient ),
class: "button is-info is-medium is-fullwidth" %>
</span>

<span>
<%= link "To Patient List ", to: Routes.pt_path(@conn, :index),
       class: "button is-link"  %>

</span>

lib/angio_web/templates/info_coronary/new.html.eex
<h4 class="title is-4 has-text-centered">New Angio Info Form</h4>
<div class="element_info">
  Patient : <%= render AngioWeb.SharedView, "_patient_info.html", patient:
  @patient %>
</div>

<%= render "form.html", Map.put(assigns, :action,
    Routes.pt_angio_path(@conn, :create, @patient)) %>

<span><%= link "Back To Angio Info", to: Routes.pt_angio_path(@conn,
      :index, @patient), class: "button is-link" %></span>

lib/angio_web/templates/info_coronary/show.html.eex
<% import  Angio.Caths.Cor_diagram_calcs  %>
<% alias Angio.Caths.Cor_diagram_calcs %>

<div class="element_info">
    Patient :
    <%= render  AngioWeb.SharedView, "_patient_info.html", patient: @patient %>
</div>
<ul>

  <li>
    <strong>Info cor diagnostic status,:</strong>
    <%= @info_coronary.info_cor_diagnostic_status %>
  </li>


  <li>
    <strong>Info cor date:</strong>
    <%= @info_coronary.info_cor_date %>
  </li>

  <li>
    <strong>Info cor arrival dt:</strong>
    <%= @info_coronary.info_cor_arrival_dt %>
  </li>

  <li>
    <strong>Info cor arrival tm:</strong>
    <%= @info_coronary.info_cor_arrival_tm %>
  </li>

  <li>
    <strong>Info cor start tm:</strong>
    <%= @info_coronary.info_cor_start_tm %>
  </li>

  <li>
    <strong>Info cor end tm:</strong>
    <%= @info_coronary.info_cor_end_tm %>
  </li>

  <li>
    <strong>Info exam num:</strong>
    <%= @info_coronary.info_exam_num %>
  </li>

  <li>
    <strong>Info cor main reason:</strong>
    <%= @info_coronary.info_cor_main_reason %>
  </li>

  <li>
    <strong>Icd10cm code 1:</strong>
    <%= @info_coronary.icd10cm_code_1 %>
  </li>

  <li>
    <strong>Icd10cm code 2:</strong>
    <%= @info_coronary.icd10cm_code_2 %>
  </li>

  <li>
    <strong>Icd10cm code 3:</strong>
    <%= @info_coronary.icd10cm_code_3 %>
  </li>

  <li>
    <strong>Icd10cm code 4:</strong>
    <%= @info_coronary.icd10cm_code_4 %>
  </li>

  <li>
    <strong>Info cor normal natives yn:</strong>
    <%= @info_coronary.info_cor_normal_natives_yn %>
  </li>

  <li>
    <strong>Info cor anomalies yn:</strong>
    <%= @info_coronary.info_cor_anomalies_yn %>
  </li>

  <li>
    <strong>Info cor dis ves num:</strong>
    <%= @info_coronary.info_cor_dis_ves_num %>
  </li>

  <li>
    <strong>Info cor prior interv yn:</strong>
    <%= @info_coronary.info_cor_prior_interv_yn %>
  </li>

  <li>
    <strong>Info cor grafts yn:</strong>
    <%= @info_coronary.info_cor_grafts_yn %>
  </li>

  <li>
    <strong>Info cor grafts dis yn:</strong>
    <%= @info_coronary.info_cor_grafts_dis_yn %>
  </li>

  <li>
    <strong>Info cor cabg prior dt:</strong>
    <%= @info_coronary.info_cor_cabg_prior_dt %>
  </li>

  <li>
    <strong>Info cor grafts implanted num:</strong>
    <%= @info_coronary.info_cor_grafts_implanted_num %>
  </li>

  <li>
    <strong>Info cor grafts patent num:</strong>
    <%= @info_coronary.info_cor_grafts_patent_num %>
  </li>

  <li>
    <strong>Info cor rx recommend:</strong>
    <%= @info_coronary.info_cor_rx_recommend %>
  </li>

  <li>
    <strong>Info cor notes:</strong>
    <%= @info_coronary.info_cor_notes %>
  </li>

  <li>
    <strong>Cor les count:</strong>
    <%= @info_coronary.cor_les_count %>
  </li>

</ul>


<div class="frame_2">
<span><%= link "Edit", to: Routes.pt_angio_path(@conn, :edit,
@patient, @info_coronary), class: "button is-link"%>
</span>
<span>
<%= link "Back To Lab", to: Routes.pt_angio_path(@conn, :index,
@patient) , class: "button is-link"%>
</span>
</div>