lib/angio_web/router.ex
defmodule AngioWeb.Router do
  use AngioWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/graphql", Absinthe.Plug, schema: AngioWeb.Schema)

  forward(
    "/graphiql",
    Absinthe.Plug.GraphiQL,
    schema: AngioWeb.Schema,
    interface: :simple,
    context: %{pubsub: AngioWeb.Endpoint}
  )

  scope "/", AngioWeb do
    pipe_through(:browser)
    live("/counter", CounterLive)

    #    live "/thermostat", ThermostatLive
    # in Index
    # <li><%= link "Thermostat", to: Routes.live_path(@conn, AngioWeb.ThermostatLive) %></li>

    get("/", PageController, :index)
    post("/patients/search_patients", PatientController, :search_patients)
    ########Routes for field Help
    post("/definitions/search_instructions", DefinitionController, :search_instructions)
    post( "/definitions/search_support_definitions",  DefinitionController, :search_support_definitions)
    post("/definitions/search_notes", DefinitionController, :search_notes)
    post("/definitions/search_option_definitions",DefinitionController,:search_option_definitions)
       #####################
    post("/definitions/search_definitions", DefinitionController, :search_definitions)
    post("/defs_tables/search_in_tables", Defs_tableController, :search_in_tables)

    resources "/patients", PatientController, as: :pt do
      # resources("/contacts", ContactController)
      ########## CORONARY ANGIO#################
      resources(
        "/info_coronaries",
        Info_coronaryController,
        only: [:index, :new, :create],
        as: :angio
      )

      resources "/info_coronaries", Info_coronaryController,
        except: [:index, :new, :create],
        as: :angio do
        resources("/care_episodes", Care_episodeController, as: :episode)
        resources("/proc_episodes", Proc_episodeController, as: :proc_episode)
        resources("/cor_collaterals", Cor_collateralController, as: :collateral)
        resources("/cor_anatomies", Cor_anatomyController, as: :anatomy)
        resources("/cor_lesions", Cor_lesionController, as: :lesion)
        resources("/cath_grafts", Cath_graftController, as: :graft)
        resources("/sats_pressures", Sats_pressureController, as: :satpres)

        resources("/angio_report", Angio_reportController, as: :report)
        post("/choose_report", Angio_reportController, :choose_report)
        resources("/Cor_tree", Cor_treeController, as: :cor_tree)
        
        # resources("/reasons", ReasonController)
        # resources("/cath_clinicals", Cath_clinicalController, as: :clinical)
        # resources("/cath_stresses", Cath_stressController, as: :stress)
        resources("/cath_events", Cath_eventController, as: :event)
        # resources("/cath_report", Cath_reportController, as: :cath_report)
        resources("/lventricles", LventricleController, as: :lv)
        resources("/cath_meds", Cath_medController, as: :cathmed)
        resources("/cath_radiations", Cath_radiationController, as: :radiation)
      end

      ## end for info_coronaries
    end

    ## end for partients
    ########## DEFINITIONS OF FIELDS #########
    resources("/defs_tables", Defs_tableController)

    resources "/definitions", DefinitionController do
      resources("/defs_sentences", Defs_sentenceController)
      resources("/defs_codes", Defs_codeController)

      resources "/defs_options", Defs_optionController do
        resources("/opts_codes", Opts_codeController, only: [:index, :new, :create])
        resources("/opts_codes", Opts_codeController)
        resources("/opts_sentences", Opts_sentenceController)
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", AngioWeb do
  #   pipe_through :api
  # end
end

lib/angio/canons/opts_sentence.ex
defmodule Angio.Canons.Opts_sentence do
  use Ecto.Schema
  import Ecto.Changeset

  schema "opts_sentences" do
    field(:definition_id, :integer)
    field(:language, :string)
    field(:note, :string)
    field(:sentence, :string)
    field(:defs_option_id, :integer)
    timestamps()
  end

  @doc false
  def changeset(opts_sentence, attrs) do
    opts_sentence
    |> cast(attrs, [:language, :sentence, :note, :definition_id])
    # |> validate_required([:language, :sentence, :note, :definition_id])
    |> validate_required([])
  end
end

lib/angio_web/controllers/opts_sentence_controller.ex
defmodule AngioWeb.Opts_sentenceController do
  use AngioWeb, :controller

  alias Angio.Canons
  alias Angio.Canons.Opts_sentence
  alias Angio.Repo
  alias Angio.Canons.Language

  import AngioPlug

  plug(:scrub_params, "opts_sentence" when action in [:create, :update])

  plug(:assign_defs_option)
  plug(:assign_definition)
  plug(:assign_all_defs_options)
  plug(:load_defs_codes)
  plug(:load_languages)

  def index(conn, _params) do
    opts_sentences = Canons.list_opts_sentences(conn)
    render(conn, "index.html", opts_sentences: opts_sentences)
  end

  def new(conn, _params) do
    changeset = Canons.change_opts_sentence(%Opts_sentence{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"opts_sentence" => opts_sentence_params}) do
    changeset =
      conn.assigns[:defs_option]
      |> Ecto.build_assoc(:opts_sentences)
      |> Opts_sentence.changeset(opts_sentence_params)

    case Repo.insert(changeset) do
      {:ok, _opts_sentence} ->
        conn
        |> put_flash(:info, "Option Sentence created successfully.")
        |> redirect(
          to:
            Routes.definition_defs_option_opts_sentence_path(
              conn,
              :index,
              conn.assigns[:definition],
              conn.assigns[:defs_option]
            )
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  #################################
  def show(conn, %{"id" => id}) do
    opts_sentence = Canons.get_opts_sentence!(id)
    render(conn, "show.html", opts_sentence: opts_sentence)
  end

  def edit(conn, %{"id" => id}) do
    opts_sentence = Canons.get_opts_sentence!(id)
    changeset = Canons.change_opts_sentence(opts_sentence)
    render(conn, "edit.html", opts_sentence: opts_sentence, changeset: changeset)
  end

  def update(conn, %{"id" => id, "opts_sentence" => opts_sentence_params}) do
    opts_sentence = Canons.get_opts_sentence!(id)

    case Canons.update_opts_sentence(opts_sentence, opts_sentence_params) do
      {:ok, _opts_sentence} ->
        conn
        |> put_flash(:info, "Options Pick-List Item sentence updated successfully.")
        |> redirect(
          to:
            Routes.definition_defs_option_opts_sentence_path(
              conn,
              :index,
              conn.assigns[:definition],
              conn.assigns[:defs_option]
            )
        )

      # |> redirect(to: Routes.opts_sentence_path(conn, :show, opts_sentence))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", opts_sentence: opts_sentence, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    opts_sentence = Canons.get_opts_sentence!(id)
    {:ok, _opts_sentence} = Canons.delete_opts_sentence(opts_sentence)

    conn
    |> put_flash(:info, "Opts sentence deleted successfully.")
    |> redirect(
      to:
        Routes.definition_defs_option_opts_sentence_path(
          conn,
          :index,
          conn.assigns[:definition],
          conn.assigns[:defs_option]
        )
    )

    # |> redirect(to: Routes.opts_sentence_path(conn, :index))
  end

  ###########################
  defp load_languages(conn, _) do
    query =
      Language
      |> Language.alphabetical()
      |> Language.names_and_codes()

    languages = Angio.Repo.all(query)
    assign(conn, :languages, languages)
  end

  defp assign_defs_option(conn, _opts) do
    case conn.params do
      %{"defs_option_id" => defs_option_id} ->
        case Repo.get(Angio.Canons.Defs_option, defs_option_id) do
          # nil -> invalid_user(conn)
          defs_option ->
            assign(conn, :defs_option, defs_option)
        end

      _ ->
        conn
    end
  end

  ####################
  ####################
  defp load_defs_codes(conn, _opts) do
    case conn.params do
      %{"definition_id" => definition_id} ->
        query = Canons.defs_codes(definition_id)

        defs_code = Repo.all(query)
        assign(conn, :defs_code, defs_code)

      _ ->
        conn
    end
  end

  ###################

  ####################
  defp assign_all_defs_options(conn, _opts) do
    case conn.params do
      %{"definition_id" => definition_id} ->
        query = Canons.all_defs_options(definition_id)
        all_defs_options = Repo.all(query)
        assign(conn, :all_defs_options, all_defs_options)

      _ ->
        conn
    end
  end

  #####################
end

lib/angio_web/views/opts_sentence_view.ex
defmodule AngioWeb.Opts_sentenceView do
  use AngioWeb, :view
end

lib/angio_web/templates/opts_sentence/edit.html.eex
<h4 class="title is-4 has-text-centered">Editing Sentences  For an Option,  Pick-List Item</h4>
<div class="element_info">
    Option Sentences For
    <%= render  AngioWeb.SharedView, "_definition_info.html", definition: @definition %>
</div>
 

    <%= render "form.html", changeset: @changeset, languages: @languages,
    action: Routes.definition_defs_option_opts_sentence_path(@conn, :update, 
        @definition, @defs_option, @opts_sentence) %>

    <%= link "Back To Option Sentence", to:  Routes.definition_defs_option_opts_sentence_path(@conn, :create,
@definition, @defs_option),  
class: "button  is-link"%>


   

lib/angio_web/templates/opts_sentence/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
 



<div class = "columns">

<div class = "column is-4">
<%= if assigns[:languages] do %>
<div class="field">
    <label class="label"> Language </label>
          <div class="control">
            <div class="select is-primary">
              <%= select(f,
:language,  @languages,
prompt: "---Select---",
class: "form-control")
              %>
            </div>
            <!--select---->
            <%= error_tag f, :language   %>
            <span class="help"></span>
          </div>
          <!--control---->
        </div>
        <!---field--->
<% end %>
</div><!------column---------------->

<div class = "column is-8">

<div class="field">
          <label class="label">Sentence For Report </label>
          <div class="control">
            <%= text_input f, :sentence, class: "input", type: "text",
            placeholder: "sentence", required: false %> 
            <%= error_tag f,
            :patnts_father_name %>
          </div>
          <p class="help"></p>
        </div>
        <!--field---->


</div><!------column---------------->
</div><!----------columns------------>
<div class="columns">
<div class = "column">

<div class="field">
          <label class="label">Notes </label>
          <div class="control">
            <%= text_input f, :note, class: "textarea", type: "text",
            placeholder: "note", required: false %> 
            <%= error_tag f,
            :note %>
          </div>
          <p class="help"></p>
        </div>
        <!--field---->

</div><!------column---------------->

</div><!------columns------------------->












 

  
  


 
  
  
  <div>
    <%= submit "Save and Continue", class: "button is-info is-large is-fullwidth " %>

  </div>
<% end %>

lib/angio_web/templates/opts_sentence/index.html.eex
<h4 class="title is-4 has-text-centered">Listing Sentences  For an Option,  Pick-List Item</h4>
<div class="element_info">
    Sentences  for Option:   <%= "#{@defs_option.selection_text}" %>
    <br>
    Of <%= render  AngioWeb.SharedView, "_definition_info.html", definition: @definition %>
</div>
<table class="table is-bordered
                    is-striped
                    is-full-width
                    is-hoverable">

  <thead class="thead">

    <tr>
      <th>Language</th>
      <th>Sentence</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
<%= for opts_sentence <- @opts_sentences do %>
    <tr>
      <td><%= opts_sentence.language %></td>
      <td><%= opts_sentence.sentence %></td>
    

      <td>
<%= link "Show",
to: Routes.definition_defs_option_opts_sentence_path(@conn, :show,
                                @definition,
                                @defs_option, opts_sentence),
                            class: "button is-primary is-small" %>
      
      </td>
      <td>
         <%= link "Edit", to: Routes.definition_defs_option_opts_sentence_path(@conn, :edit,
                                @definition ,
                                @defs_option, opts_sentence),
                            class: "button is-primary is-small" %>
        
        </td>
        <td>
      
<%= link "Delete", to:  Routes.definition_defs_option_opts_sentence_path(@conn, :delete,
          @definition, @defs_option, opts_sentence), method: :delete, data: [confirm: "Are you sure?"],
        class: "button is-small is-danger" %>
     
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<span>
     <%= link  "New Sentence For Option: " <> "#{@defs_option.selection_text}",
  to:  Routes.definition_defs_option_opts_sentence_path(@conn, :new, @definition, @defs_option),
class: "button is-info is-large is-fullwidth"%>
</span>

<span>
 <%= link "Back Pick-List",  to: Routes.definition_defs_option_path(@conn, :index, @definition),
class: "button is-link "  %>
</span>


<span>
<%= link "To Field List", to: Routes.definition_path(@conn, :index),
       class: "button is-link"  %>
</span><%#= link "New Opts sentence", to: Routes.opts_sentence_path(@conn, :new) %></span>

lib/angio_web/templates/opts_sentence/new.html.eex
<div class="title_form">
<h4 class="title is-4 has-text-centered">Form For an Option Sentence  Pick-List Item</h4>
</div><!---title form------------------->
<div class="element_info">
    Option   <%= "#{@defs_option.selection_text}" %>
    <br>
    Of <%= render  AngioWeb.SharedView, "_definition_info.html", definition: @definition %>
</div>
      
      <%= render "form.html", changeset: @changeset,
      languages: @languages,
        action: Routes.definition_defs_option_opts_sentence_path(@conn, :create, @definition, @defs_option)  %>
      <span>
        
        <%= link "Back To Options Sentences", to:  Routes.definition_defs_option_opts_sentence_path(@conn, :create,
            @definition, @defs_option),  class: "button is-primary"%>

    </span>

    

lib/angio_web/templates/opts_sentence/show.html.eex
<div class="title is-4 has-text-centered">
      <p> Showing Option Sentence</p>
    </div>
    
<div class="element_info">
   
    <%= render  AngioWeb.SharedView, "_definition_info.html", definition: @definition %>
</div>
 
<ul class = "frame_2">

  <li>
    <strong>Language:</strong>
    <%= @opts_sentence.language %>
  </li>

  <li>
    <strong>Sentence:</strong>
    <%= raw @opts_sentence.sentence %>
  </li>

  <li>
    <strong>Note:</strong>
    <%= raw @opts_sentence.note %>
  </li>

  <li>
    <strong>Definition:</strong>
    <%= @opts_sentence.definition_id %>
  </li>

</ul>
<span>
   <%= link "Edit", to: Routes.definition_defs_option_opts_sentence_path(@conn, :edit, @definition , 
   @defs_option, @opts_sentence), class: "button  is-link" %>
   </span>
<span>
   <%= link "Back Options Sentences", to: Routes.definition_defs_option_opts_sentence_path(@conn, :index, 
   @definition, @defs_option),
    class: "button  is-link"%>
</span>