lib/angio_web/router.ex
defmodule AngioWeb.Router do
  use AngioWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_flash)
    plug(Phoenix.LiveView.Flash)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/graphql", Absinthe.Plug, schema: AngioWeb.Schema)

  forward(
    "/graphiql",
    Absinthe.Plug.GraphiQL,
    schema: AngioWeb.Schema,
    interface: :simple,
    context: %{pubsub: AngioWeb.Endpoint}
  )

  scope "/", AngioWeb do
    pipe_through(:browser)
    live("/counter", CounterLive)

    #    live "/thermostat", ThermostatLive
    # in Index
    # <li><%= link "Thermostat", to: Routes.live_path(@conn, AngioWeb.ThermostatLive) %></li>

    get("/", PageController, :index)
    post("/patients/search_patients", PatientController, :search_patients)
    ########Routes for field Help
    post("/definitions/search_instructions", DefinitionController, :search_instructions)
    post( "/definitions/search_support_definitions",  DefinitionController, :search_support_definitions)
    post("/definitions/search_notes", DefinitionController, :search_notes)
    post("/definitions/search_option_definitions",DefinitionController,:search_option_definitions)
       #####################
    post("/definitions/search_definitions", DefinitionController, :search_definitions)
    post("/defs_tables/search_in_tables", Defs_tableController, :search_in_tables)

    resources "/patients", PatientController, as: :pt do
      # resources("/contacts", ContactController)
      ########## CORONARY ANGIO#################
      resources(
        "/info_coronaries",
        Info_coronaryController,
        only: [:index, :new, :create],
        as: :angio
      )

      resources "/info_coronaries", Info_coronaryController,
        except: [:index, :new, :create],
        as: :angio do
        resources("/care_episodes", Care_episodeController, as: :episode)
        resources("/proc_episodes", Proc_episodeController, as: :proc_episode)
        resources("/cor_collaterals", Cor_collateralController, as: :collateral)
        resources("/cor_anatomies", Cor_anatomyController, as: :anatomy)
        resources("/cor_lesions", Cor_lesionController, as: :lesion)
        resources("/cath_grafts", Cath_graftController, as: :graft)
        resources("/sats_pressures", Sats_pressureController, as: :satpres)

        resources("/angio_report", Angio_reportController, as: :report)
        post("/choose_report", Angio_reportController, :choose_report)
        resources("/Cor_tree", Cor_treeController, as: :cor_tree)
        
        # resources("/reasons", ReasonController)
        # resources("/cath_clinicals", Cath_clinicalController, as: :clinical)
        # resources("/cath_stresses", Cath_stressController, as: :stress)
        resources("/cath_events", Cath_eventController, as: :event)
        # resources("/cath_report", Cath_reportController, as: :cath_report)
        resources("/lventricles", LventricleController, as: :lv)
        resources("/cath_meds", Cath_medController, as: :cathmed)
        resources("/cath_radiations", Cath_radiationController, as: :radiation)
      end

      ## end for info_coronaries
    end

    ## end for partients
    ########## DEFINITIONS OF FIELDS #########
    resources("/defs_tables", Defs_tableController)

    resources "/definitions", DefinitionController do
      resources("/defs_sentences", Defs_sentenceController)
      resources("/defs_codes", Defs_codeController)

      resources "/defs_options", Defs_optionController do
        resources("/opts_codes", Opts_codeController, only: [:index, :new, :create])
        resources("/opts_codes", Opts_codeController)
        resources("/opts_sentences", Opts_sentenceController)
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", AngioWeb do
  #   pipe_through :api
  # end
end

lib/angio/caths/cath_graft.ex
defmodule Angio.Caths.Cath_graft do
  use Ecto.Schema
  import Ecto.Changeset

  schema "cath_grafts" do
    field(:graft_prox_sten_prior_treated_dt, :date)
    field(:graft_ostial_sten_ivus, :string)
    field(:graft_prox_sten_ivus, :string)
    field(:graft_mid_sten_device_present_yn, :boolean, default: false)
    field(:graft_dist_sten_prior_treated_dt, :date)
    field(:graft_mid_sten_prior_treated_yn, :boolean, default: false)
    field(:cath_graft_conduit_type, :string)
    field(:graft_prox_sten_ffr, :string)
    field(:graft_dist_anast_prior_treated_dt, :date)
    field(:graft_dist_anast_sten_yn, :boolean, default: false)
    field(:graft_index, :string)
    field(:cath_graft_segments_sts, {:array, :string})
    field(:graft_total_occlusion_yn, :boolean, default: false)
    field(:graft_dist_sten_yn, :boolean, default: false)
    field(:graft_mid_sten_yn, :boolean, default: false)
    field(:graft_prox_sten_yn, :boolean, default: false)
    field(:graft_ostial_sten_ffr, :string)
    field(:graft_dist_sten_ivus, :string)
    field(:graft_morphology, :string)
    field(:graft_mid_sten_ffr, :string)
    field(:cath_graft_header, :string)
    field(:graft_dist_anast_sten_ffr, :string)
    field(:graft_dist_sten_ffr, :string)
    field(:graft_dist_anast_type, :string)
    field(:graft_ostial_prior_treated_dt, :date)
    field(:graft_dist_sten_prior_treated_yn, :boolean, default: false)
    field(:graft_dist_sten_device_present_yn, :boolean, default: false)
    field(:graft_ostial_prior_treated_yn, :boolean, default: false)
    field(:graft_mid_sten_prior_treated_dt, :date)
    field(:graft_prox_sten_device_present_yn, :boolean, default: false)
    field(:graft_ostial_sten_pct, :string)
    field(:cath_graft_prox_site, :string)
    field(:graft_dist_anast_prior_treated_yn, :boolean, default: false)
    field(:patient_id, :integer)
    field(:graft_ostial_sten_yn, :boolean, default: false)
    field(:cath_graft_segments_ncdr, {:array, :string})
    field(:graft_dist_anast_device_present_yn, :boolean, default: false)
    field(:graft_sten_yn, :boolean, default: false)
    field(:cath_graft_segments_main_vessel, :string)
    field(:graft_ostial_device_present_yn, :boolean, default: false)
    field(:graft_dist_anast_sten_pct, :string)
    field(:graft_prox_sten_pct, :string)
    field(:graft_notes, :string)
    field(:graft_mid_sten_ivus, :string)
    field(:cath_graft_segments_cdisc, {:array, :string})
    field(:graft_prox_sten_prior_treated_yn, :boolean, default: false)
    field(:graft_dist_anast_sten_ivus, :string)
    field(:graft_dist_sten_pct, :string)
    field(:graft_mid_sten_pct, :string)
    field(:info_coronary_id, :integer)
    timestamps()
  end

  @doc false
  def changeset(cath_graft, attrs) do
    cath_graft
    |> cast(attrs, [
      :cath_graft_header,
      :graft_morphology,
      :graft_index,
      :graft_total_occlusion_yn,
      :graft_sten_yn,
      :graft_ostial_sten_yn,
      :graft_ostial_sten_pct,
      :graft_ostial_device_present_yn,
      :graft_ostial_prior_treated_yn,
      :graft_ostial_prior_treated_dt,
      :graft_ostial_sten_ffr,
      :graft_ostial_sten_ivus,
      :graft_prox_sten_yn,
      :graft_prox_sten_pct,
      :graft_prox_sten_device_present_yn,
      :graft_prox_sten_prior_treated_yn,
      :graft_prox_sten_prior_treated_dt,
      :graft_prox_sten_ffr,
      :graft_prox_sten_ivus,
      :graft_mid_sten_yn,
      :graft_mid_sten_pct,
      :graft_mid_sten_device_present_yn,
      :graft_mid_sten_prior_treated_yn,
      :graft_mid_sten_prior_treated_dt,
      :graft_mid_sten_ffr,
      :graft_mid_sten_ivus,
      :graft_dist_sten_yn,
      :graft_dist_sten_pct,
      :graft_dist_sten_device_present_yn,
      :graft_dist_sten_prior_treated_yn,
      :graft_dist_sten_prior_treated_dt,
      :graft_dist_sten_ffr,
      :graft_dist_sten_ivus,
      :graft_dist_anast_sten_yn,
      :graft_dist_anast_type,
      :graft_dist_anast_device_present_yn,
      :graft_dist_anast_sten_pct,
      :graft_dist_anast_prior_treated_yn,
      :graft_dist_anast_prior_treated_dt,
      :graft_dist_anast_sten_ffr,
      :graft_dist_anast_sten_ivus,
      :cath_graft_prox_site,
      :cath_graft_conduit_type,
      :cath_graft_segments_main_vessel,
      :cath_graft_segments_ncdr,
      :cath_graft_segments_cdisc,
      :cath_graft_segments_sts,
      :patient_id,
      :graft_notes
    ])
    |> validate_required([])

    # |> validate_required([:cath_graft_header, :graft_morphology, :graft_index, :graft_total_occlusion_yn, :graft_sten_yn, :graft_ostial_sten_yn, :graft_ostial_sten_pct, :graft_ostial_device_present_yn, :graft_ostial_prior_treated_yn, :graft_ostial_prior_treated_dt, :graft_ostial_sten_ffr, :graft_ostial_sten_ivus, :graft_prox_sten_yn, :graft_prox_sten_pct, :graft_prox_sten_device_present_yn, :graft_prox_sten_prior_treated_yn, :graft_prox_sten_prior_treated_dt, :graft_prox_sten_ffr, :graft_prox_sten_ivus, :graft_mid_sten_yn, :graft_mid_sten_pct, :graft_mid_sten_device_present_yn, :graft_mid_sten_prior_treated_yn, :graft_mid_sten_prior_treated_dt, :graft_mid_sten_ffr, :graft_mid_sten_ivus, :graft_dist_sten_yn, :graft_dist_sten_pct, :graft_dist_sten_device_present_yn, :graft_dist_sten_prior_treated_yn, :graft_dist_sten_prior_treated_dt, :graft_dist_sten_ffr, :graft_dist_sten_ivus, :graft_dist_anast_sten_yn, :graft_dist_anast_type, :graft_dist_anast_device_present_yn, :graft_dist_anast_sten_pct, :graft_dist_anast_prior_treated_yn, :graft_dist_anast_prior_treated_dt, :graft_dist_anast_sten_ffr, :graft_dist_anast_sten_ivus, :cath_graft_prox_site, :cath_graft_conduit_type, :cath_graft_segments_main_vessel, :cath_graft_segments_ncdr, :cath_graft_segments_cdisc, :cath_graft_segments_sts, :patient_id, :graft_notes])
  end
end

lib/angio_web/controllers/cath_graft_controller.ex
defmodule AngioWeb.Cath_graftController do
  use AngioWeb, :controller
  import AngioPlug

  plug(:assign_info_coronary)
  plug(:assign_patient)

  alias Angio.Caths
  alias Angio.Caths.Cath_graft
  alias Angio.Repo
  plug(:scrub_params, "cath_graft" when action in [:create, :update])

  def index(conn, _params) do
    cath_grafts = Caths.list_cath_grafts(conn)
    render(conn, "index.html", cath_grafts: cath_grafts)
  end

  def new(conn, _params) do
    changeset = Caths.change_cath_graft(%Cath_graft{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"cath_graft" => cath_graft_params}) do
    changeset =
      conn.assigns[:info_coronary]
      |> Ecto.build_assoc(:cath_grafts)
      |> Cath_graft.changeset(cath_graft_params)

    case Repo.insert(changeset) do
      {:ok, _cath_graft} ->
        conn
        |> put_flash(:info, "Graft created successfully.")
        |> redirect(
          to:
            Routes.pt_angio_graft_path(
              conn,
              :index,
              conn.assigns[:patient],
              conn.assigns[:info_coronary]
            )
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  ############################

  def show(conn, %{"id" => id}) do
    cath_graft = Caths.get_cath_graft!(id)
    render(conn, "show.html", cath_graft: cath_graft)
  end

  def edit(conn, %{"id" => id}) do
    cath_graft = Caths.get_cath_graft!(id)
    changeset = Caths.change_cath_graft(cath_graft)
    render(conn, "edit.html", cath_graft: cath_graft, changeset: changeset)
  end

  def update(conn, %{"id" => id, "cath_graft" => cath_graft_params}) do
    cath_graft = Angio.Caths.get_cath_graft!(id)

    case Caths.update_cath_graft(cath_graft, cath_graft_params) do
      {:ok, _cath_grafts} ->
        conn
        |> put_flash(:info, " Graft updated successfully.")
        |> redirect(
          to:
            Routes.pt_angio_graft_path(
              conn,
              :index,
              conn.assigns[:patient],
              conn.assigns[:info_coronary]
            )
        )

      #########################
      # info_coronary_id_str = conn.params["info_coronary_id"]
      # info_coronary_id = String.to_integer(info_coronary_id_str)

      # changeset =
      #  Cor_lesion.changeset(%Cor_lesion{}, cor_lesion_params)
      #  |> Ecto.Changeset.put_change(
      #    :info_coronary_id,
      #    info_coronary_id
      #  )

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", cath_graft: cath_graft, changeset: changeset)
    end
  end

  ##############################
  def delete(conn, %{"id" => id}) do
    cath_graft = Caths.get_cath_graft!(id)
    {:ok, _cath_graft} = Caths.delete_cath_graft(cath_graft)

    conn
    |> put_flash(:info, "Graft  deleted successfully.")
    |> redirect(
      to:
        Routes.pt_angio_graft_path(
          conn,
          :index,
          conn.assigns[:patient],
          conn.assigns[:info_coronary]
        )
    )
  end
end

lib/angio_web/views/cath_graft_view.ex
defmodule AngioWeb.Cath_graftView do
  use AngioWeb, :view
end

lib/angio_web/templates/cath_graft/edit.html.eex
<div class="title_form">
<h4 class="title is-4 has-text-centered"> Editing Grafts</h4>
</div>

<div class="element_info">
  Patient : <%= render AngioWeb.SharedView, "_patient_info.html", patient:
  @patient %>
</div>

<div class="element_info_coronary">
<%= render AngioWeb.SharedView, "_info_coronary.html", info_coronary:
   @info_coronary%>
</div>




 <%= render "form.html", changeset: @changeset,
        cath_graft: @cath_graft,
action: Routes.pt_angio_graft_path(@conn, :update, @patient, @info_coronary,
@cath_graft ) %>

        <span>
          <%= link "Back To Grafts  List", 
  to: Routes.pt_angio_graft_path(@conn, :index,
@patient,@info_coronary) , class: "button is-link"%>
</span>
<span>
<%= link "Back To Lab",  to: Routes.pt_angio_path(@conn, :index, @patient),
class: "button is-link"   %>
 </span>

lib/angio_web/templates/cath_graft/index.html.eex
<div class="title_form">
<h4 class="title is-4 has-text-centered">List Of Grafts</h4>
</div>
<div class="element_info">
  Patient : <%= render AngioWeb.SharedView, "_patient_info.html", patient:
  @patient %>
</div>

<div class="element_info_coronary">
 <%= render AngioWeb.SharedView, "_info_coronary.html", info_coronary:
   @info_coronary%>
</div>


<% alias Angio.Canons, as: Query %>
<div class="columns">
  <div class="column is-2">
 <%#= render  AngioWeb.SharedView, "_menu_info_coronary.html",
conn: @conn, patient: @patient, info_coronary: @info_coronary %>
<%= render  AngioWeb.SharedView, "_menu_info_coronary.html", assigns %>

  </div><!----column-------------------->
<div class="column is-10 frame_2">

<table
  class="table is-bordered
                    is-striped
                    is-full-width
                    is-hoverable"
>
  <thead class="thead">
    <tr>
    <tr>
    <th>Graft Origin</th>
    <th>Distal Anastomosis</th>
      <th>Graft morphology</th>
      <th>Graft index</th>
      <th>Conduit Type</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
<%= for cath_graft <- @cath_grafts do %>
    <tr>
    <td>
   <%= cath_graft.cath_graft_prox_site %>
    </td>
   <td>
      <%= cath_graft.cath_graft_segments_cdisc %>
    </td>  
      <td>
    <% s_morphology =  Query.select_options("graft_morphology") %>
 <% v_morphology= cath_graft.graft_morphology   %>

  <ul class="list-group">
<%= raw(Query.convert_select_key( s_morphology , v_morphology)) %>
</ul>

      </td>
      <td><%= cath_graft.graft_index %></td>

      <td>
 <% s_conduit =  Query.select_options("uni_graft_conduit_type") %>
 <% v_conduit= cath_graft.cath_graft_conduit_type %>

  <ul class="list-group">
<%= raw(Query.convert_select_key( s_conduit , v_conduit)) %>
</ul>

        </td>

        <td>

   <%= link "Show", to: Routes.pt_angio_graft_path(@conn, :show, @patient, @info_coronary, cath_graft), class: "button is-primary is-small" %>

        <%#= link "Show", to: Routes.cath_graft_path(@conn, :show, cath_graft) %>



      </td>

      <td>

 <%= link "Edit", to: Routes.pt_angio_graft_path(@conn, :edit, @patient,
        @info_coronary, cath_graft), class: "button is-primary is-small" %>
      </td>


      <td>

   <%= link "Delete", to: Routes.pt_angio_graft_path(@conn, :delete,
        @patient, @info_coronary, cath_graft), method: :delete, data: [confirm:
        "Are you sure?"], class: "button is-small is-danger" %>
      </td>



    </tr>
<% end %>
  </tbody>
</table>

</div><!-------column-------------------->
</div><!-----columns------------------->
<span
  ><%= link "Insert - Add A New Graft ", to: Routes.pt_angio_graft_path(@conn, :new,
  @patient, @info_coronary), class: "button is-info is-medium is-fullwidth" %>
</span>
<span>
  <%= link "To Patient List", to: Routes.pt_path(@conn, :index), class: "button
  is-link" %>

</span>

<span>
<%= link "Back To Lab",  to: Routes.pt_angio_path(@conn, :index, @patient),
class: "button is-link"   %>
 </span>

lib/angio_web/templates/cath_graft/new.html.eex
<% alias Angio.Cath%>
<h4 class="title is-4">New Graft</h4>
<div class="element_info">
  Patient : <%= render AngioWeb.SharedView, "_patient_info.html", patient:
  @patient %>
</div>

<%= render "form.html", changeset: @changeset, action:
Routes.pt_angio_graft_path(@conn, :create, @patient, @info_coronary) %>
<%=link "Back To Graft List", to: Routes.pt_angio_graft_path(@conn, :create,
@patient, @info_coronary), class: "button is-primary"%>
<span>
<%= link "Back To Lab",  to: Routes.pt_angio_path(@conn, :index, @patient),
class: "button is-primary"   %>
 </span>

lib/angio_web/templates/cath_graft/show.html.eex
<div class="title_form">
<h4 class="title is-4 has-text-centered"> Show Cath graft</h4>
</div>

<div class="element_info">
  Patient : <%= render AngioWeb.SharedView, "_patient_info.html", patient:
  @patient %>
</div>

<div class="element_info_coronary">
<%= render AngioWeb.SharedView, "_info_coronary.html", info_coronary:
   @info_coronary%>
</div>

<ul>

  <li>
    <strong>Cath graft header:</strong>
    <%= @cath_graft.cath_graft_header %>
  </li>

  <li>
    <strong>Graft morphology:</strong>
    <%= @cath_graft.graft_morphology %>
  </li>

  <li>
    <strong>Graft index:</strong>
    <%= @cath_graft.graft_index %>
  </li>

  <li>
    <strong>Graft total occlusion yn:</strong>
    <%= @cath_graft.graft_total_occlusion_yn %>
  </li>

  <li>
    <strong>Graft sten yn:</strong>
    <%= @cath_graft.graft_sten_yn %>
  </li>

  <li>
    <strong>Graft ostial sten yn:</strong>
    <%= @cath_graft.graft_ostial_sten_yn %>
  </li>

  <li>
    <strong>Graft ostial sten pct:</strong>
    <%= @cath_graft.graft_ostial_sten_pct %>
  </li>

  <li>
    <strong>Graft ostial device present yn:</strong>
    <%= @cath_graft.graft_ostial_device_present_yn %>
  </li>

  <li>
    <strong>Graft ostial prior treated yn:</strong>
    <%= @cath_graft.graft_ostial_prior_treated_yn %>
  </li>

  <li>
    <strong>Graft ostial prior treated dt:</strong>
    <%= @cath_graft.graft_ostial_prior_treated_dt %>
  </li>

  <li>
    <strong>Graft ostial sten ffr:</strong>
    <%= @cath_graft.graft_ostial_sten_ffr %>
  </li>

  <li>
    <strong>Graft ostial sten ivus:</strong>
    <%= @cath_graft.graft_ostial_sten_ivus %>
  </li>

  <li>
    <strong>Graft prox sten yn:</strong>
    <%= @cath_graft.graft_prox_sten_yn %>
  </li>

  <li>
    <strong>Graft prox sten pct:</strong>
    <%= @cath_graft.graft_prox_sten_pct %>
  </li>

  <li>
    <strong>Graft prox sten device present yn:</strong>
    <%= @cath_graft.graft_prox_sten_device_present_yn %>
  </li>

  <li>
    <strong>Graft prox sten prior treated yn:</strong>
    <%= @cath_graft.graft_prox_sten_prior_treated_yn %>
  </li>

  <li>
    <strong>Graft prox sten prior treated dt:</strong>
    <%= @cath_graft.graft_prox_sten_prior_treated_dt %>
  </li>

  <li>
    <strong>Graft prox sten ffr:</strong>
    <%= @cath_graft.graft_prox_sten_ffr %>
  </li>

  <li>
    <strong>Graft prox sten ivus:</strong>
    <%= @cath_graft.graft_prox_sten_ivus %>
  </li>

  <li>
    <strong>Graft mid sten yn:</strong>
    <%= @cath_graft.graft_mid_sten_yn %>
  </li>

  <li>
    <strong>Graft mid sten pct:</strong>
    <%= @cath_graft.graft_mid_sten_pct %>
  </li>

  <li>
    <strong>Graft mid sten device present yn:</strong>
    <%= @cath_graft.graft_mid_sten_device_present_yn %>
  </li>

  <li>
    <strong>Graft mid sten prior treated yn:</strong>
    <%= @cath_graft.graft_mid_sten_prior_treated_yn %>
  </li>

  <li>
    <strong>Graft mid sten prior treated dt:</strong>
    <%= @cath_graft.graft_mid_sten_prior_treated_dt %>
  </li>

  <li>
    <strong>Graft mid sten ffr:</strong>
    <%= @cath_graft.graft_mid_sten_ffr %>
  </li>

  <li>
    <strong>Graft mid sten ivus:</strong>
    <%= @cath_graft.graft_mid_sten_ivus %>
  </li>

  <li>
    <strong>Graft dist sten yn:</strong>
    <%= @cath_graft.graft_dist_sten_yn %>
  </li>

  <li>
    <strong>Graft dist sten pct:</strong>
    <%= @cath_graft.graft_dist_sten_pct %>
  </li>

  <li>
    <strong>Graft dist sten device present yn:</strong>
    <%= @cath_graft.graft_dist_sten_device_present_yn %>
  </li>

  <li>
    <strong>Graft dist sten prior treated yn:</strong>
    <%= @cath_graft.graft_dist_sten_prior_treated_yn %>
  </li>

  <li>
    <strong>Graft dist sten prior treated dt:</strong>
    <%= @cath_graft.graft_dist_sten_prior_treated_dt %>
  </li>

  <li>
    <strong>Graft dist sten ffr:</strong>
    <%= @cath_graft.graft_dist_sten_ffr %>
  </li>

  <li>
    <strong>Graft dist sten ivus:</strong>
    <%= @cath_graft.graft_dist_sten_ivus %>
  </li>

  <li>
    <strong>Graft dist anast sten yn:</strong>
    <%= @cath_graft.graft_dist_anast_sten_yn %>
  </li>

  <li>
    <strong>Graft dist anast type:</strong>
    <%= @cath_graft.graft_dist_anast_type %>
  </li>

  <li>
    <strong>Graft dist anast device present yn:</strong>
    <%= @cath_graft.graft_dist_anast_device_present_yn %>
  </li>

  <li>
    <strong>Graft dist anast sten pct:</strong>
    <%= @cath_graft.graft_dist_anast_sten_pct %>
  </li>

  <li>
    <strong>Graft dist anast prior treated yn:</strong>
    <%= @cath_graft.graft_dist_anast_prior_treated_yn %>
  </li>

  <li>
    <strong>Graft dist anast prior treated dt:</strong>
    <%= @cath_graft.graft_dist_anast_prior_treated_dt %>
  </li>

  <li>
    <strong>Graft dist anast sten ffr:</strong>
    <%= @cath_graft.graft_dist_anast_sten_ffr %>
  </li>

  <li>
    <strong>Graft dist anast sten ivus:</strong>
    <%= @cath_graft.graft_dist_anast_sten_ivus %>
  </li>

  <li>
    <strong>Cath graft prox site:</strong>
    <%= @cath_graft.cath_graft_prox_site %>
  </li>

  <li>
    <strong>Cath graft conduit type:</strong>
    <%= @cath_graft.cath_graft_conduit_type %>
  </li>

  <li>
    <strong>Cath graft segments main vessel:</strong>
    <%= @cath_graft.cath_graft_segments_main_vessel %>
  </li>

  <li>
    <strong>Cath graft segments ncdr:</strong>
    <%= @cath_graft.cath_graft_segments_ncdr %>
  </li>

  <li>
    <strong>Cath graft segments cdisc:</strong>
    <%= @cath_graft.cath_graft_segments_cdisc %>
  </li>

  <li>
    <strong>Cath graft segments sts:</strong>
    <%= @cath_graft.cath_graft_segments_sts %>
  </li>

  <li>
    <strong>Patient:</strong>
    <%= @cath_graft.patient_id %>
  </li>

  <li>
    <strong>Graft notes:</strong>
    <%= @cath_graft.graft_notes %>
  </li>

</ul>
<span>
    <%= link "Edit Graft", to: Routes.pt_angio_graft_path(@conn, :edit, @patient,
  @info_coronary, @cath_graft ), class: "button is-primary"%>
</span>
<span>
  <%= link "Back To Grafts List", to: Routes.pt_angio_graft_path(@conn, :index,
  @patient, @info_coronary) , class: "button is-primary"%>
</span>
</span>
<span>
<%= link "Back To Lab",  to: Routes.pt_angio_path(@conn, :index, @patient),
class: "button is-primary"   %>
 </span>